import jsPDF from "jspdf";

export const exportPDF = (
  title: string,
  content: string
) => {
  try {
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // PAGE SETTINGS
    const pageWidth =
      pdf.internal.pageSize.getWidth();

    const pageHeight =
      pdf.internal.pageSize.getHeight();

    const marginLeft = 20;

    const marginTop = 25;

    const contentWidth =
      pageWidth - 40;

    // CLEAN CONTENT
    // Removes unsupported symbols
    // while preserving clean English export
    const cleanedContent =
      content
        .replace(
          /[^\u0000-\u00FF]/g,
          ""
        )
        .replace(/\t/g, " ")
        .replace(/\r/g, "");

    // TITLE
    pdf.setFont(
      "times",
      "bold"
    );

    pdf.setFontSize(18);

    pdf.text(
      title,
      pageWidth / 2,
      marginTop,
      {
        align: "center",
      }
    );

    // SUBTITLE
    pdf.setFont(
      "times",
      "normal"
    );

    pdf.setFontSize(11);

    pdf.text(
      "Generated by HaigoraAI",
      pageWidth / 2,
      marginTop + 8,
      {
        align: "center",
      }
    );

    // CONTENT
    pdf.setFont(
      "times",
      "normal"
    );

    pdf.setFontSize(12);

    const splitContent =
      pdf.splitTextToSize(
        cleanedContent,
        contentWidth
      );

    let cursorY =
      marginTop + 20;

    const lineHeight = 8;

    splitContent.forEach(
      (line: string) => {
        // ADD NEW PAGE
        if (
          cursorY >
          pageHeight - 20
        ) {
          pdf.addPage();

          cursorY = 20;
        }

        pdf.text(
          line,
          marginLeft,
          cursorY,
          {
            align: "left",
            maxWidth:
              contentWidth,
          }
        );

        cursorY +=
          lineHeight;
      }
    );

    // FOOTER PAGE NUMBERS
    const totalPages =
      pdf.getNumberOfPages();

    for (
      let i = 1;
      i <= totalPages;
      i++
    ) {
      pdf.setPage(i);

      pdf.setFontSize(10);

      pdf.setFont(
        "times",
        "italic"
      );

      pdf.text(
        `Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        {
          align: "center",
        }
      );
    }

    // DOWNLOAD
    pdf.save(
      `${title
        .replace(/\s+/g, "_")
        .toLowerCase()}.pdf`
    );
  } catch (error) {
    console.error(
      "PDF Export Error:",
      error
    );

    alert(
      "Failed to export PDF."
    );
  }
};